project_name: apizza

before:
  hooks:
    - go mod tidy
    - go generate ./...

release:
  github:
    owner: harrybrwn
    name: apizza
  prerelease: auto
  draft: false

builds:
  - binary: apizza
    id: apizza
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    ldflags:
      - -s -w
      - -X github.com/harrybrwn/apizza/cmd.version={{.Version}}
    goos: [linux, darwin, windows]
    goarch: [386, amd64, arm64]
    ignore:
      - { goos: darwin,  goarch: 386   }
      - { goos: darwin,  goarch: arm64 }
      - { goos: windows, goarch: arm64 }

archives:
  - replacements: &replacements
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: 32-bit
      amd64: 64-bit
      arm64: arm64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - docs/*

nfpms:
  - <<: &description
      description: Command line tool for ordering Dominos pizza.
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements: *replacements
    maintainer: Harry Brown <harrybrown98@gmail.com>
    license: Apache 2.0
    formats:
      - deb
      - rpm
    bindir: /usr/local/bin

brews:
  - <<: *description
    name: apizza
    github:
      owner: harrybrwn
      name: homebrew-tap
    homepage: https://github.com/harrybrwn/apizza
    commit_author:
      name: apizza-releasebot
      email: harrybrown98@gmail.com
    folder: Formula
    test: |
      system "#{bin}/apizza --version"
    install: |
      bin.install "apizza"

snapcrafts:
  - <<: *description
    name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    summary: Command line tool for ordering Dominos pizza.
    grade: stable
    confinement: classic
    publish: false

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Version }}-{{ .ShortCommit }}"

changelog:
  skip: true
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
