# This file was generated by GoReleaser. DO NOT EDIT.
class Apizza < Formula
  desc "Command line tool for ordering Dominos pizza."
  homepage "https://github.com/harrybrwn/apizza"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/harrybrwn/apizza/releases/download/v0.0.3/apizza_0.0.3_MacOS_64-bit.tar.gz"
    sha256 "8461cde7cf34ac87af6e44fbb9935a329422fdd212353c83df58f39979a951ce"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/harrybrwn/apizza/releases/download/v0.0.3/apizza_0.0.3_Linux_64-bit.tar.gz"
      sha256 "89d1ad0c58692a1d58f6c1a9ee4f23c0ce239cba5fdc24a3c4762833ef3d6a15"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/harrybrwn/apizza/releases/download/v0.0.3/apizza_0.0.3_Linux_arm64.tar.gz"
        sha256 "88b6af043ed3959dd56858d9499eb3203280cadfde77b2ba00696a620ef3161e"
      else
      end
    end
  end

  def install
    bin.install "apizza"
  end

  test do
    system "#{bin}/apizza --version"
  end
end
